### ISSUE TITLE
Issue with Stacks NFT collection not loading properly in Hiro wallet

### ISSUE THREAD

**Issue by DeeList** [hirosystems/token-metadata-api#158]
NFTs in the Stacks NFT collection are not loading properly in the Hiro wallet vs Gamma.io site displays. Users are experiencing slow loading times or NFTs not loading at all. 
related (https://github.com/hirosystems/wallet/issues/3712)

Comparison screenshots:

Hiro Wallet
![hiro1](https://github.com/hirosystems/wallet/assets/132958967/4cd3dcbc-9efb-44ca-a005-fff6385c722b)

Gamma.io
![gamma1](https://github.com/hirosystems/wallet/assets/132958967/70532e66-f217-485a-a279-a6908c8ce383)

**Comment by rafaelcr** [comment]
Hi @DeeList, the API only returns image links as they were declared in the token's metadata JSON document. If these links break for any reason, image fetching may become impossible from the wallet. Given your example, I assume Gamma keeps a local copy of the NFT artwork just in case something like this happens.

Unfortunately there's nothing the API can do to remedy this issue. The NFT creators should move their images to a new location, update their metadata JSONs, and send a SIP-019 notification to refresh it on indexers (including this API). cc @markmhx

**Comment by 314159265359879** [comment]
@rafaelcr I am not sure the images not loading is the issue here. This is from the user's report:
![image](https://github.com/hirosystems/token-metadata-api/assets/33360391/1a7606db-2d36-4f44-94b3-53a000ac82ee)

There should not be that many tokens shown in the first place. Here is another example like that. The following wallet, SP3N0TH3N7BDG4WBSYV6FE2ASSAPEGWK47EEWD9TV,  has two:
boombox 10th edition's (contract: SP1QK1AZ24R132C0D84EEQ8Y2JDHARDR58R72E1ZW.boomboxes-cycle-32 ) but the wallet shows a lot more, loads more (some appear to be loading, which is weird because it is already downloaded?):

https://github.com/hirosystems/token-metadata-api/assets/33360391/99cadf2a-69b4-47af-bb34-d6c0b29a2faf
